/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyApp3;

import org.junit.Assert;
import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void aSmallTest() {
        Assert.assertEquals(1, 1);
    }
}
